### ISSUE TITLE
Which shell does guard-shell use and can it be changed? (Documentation issue)

### ISSUE THREAD

**Issue by matt17r** [hawx/guard-shell#28]
I can't tell by looking at the documentation or the source which shell `guard-shell` is using.

By running `` `printf "\n\n%s\n\n" $0` `` in a `watch` block it appears to be running using `sh`.

Is this behaviour worth documenting? Is it possible to specify a different shell to be used throughout a `guard :shell` block? I'm happy to write up some documentation and submit a PR I just don't know the answers, nor how to figure them out...

**Comment by hawx** [comment]
I guess the name "guard-shell" is a bit confusing in this respect since _it_ doesn't actually do anything with the shell, it just calls [puts](https://github.com/hawx/guard-shell/blob/master/lib/guard/shell.rb#L23) on the argument if truthy. The backticks are doing the subshelling, so maybe take a look at the Ruby docs for that.
